- bindings/src/enhancers.rs
- rust/benches/enhancers.rs
- rust/src/enhancers/actions.rs
- rust/src/enhancers/cache.rs
- rust/src/enhancers/mod.rs
Removes the `Cache` trait and turns the implementation into, essentially, an `Option<LruCache>`.
> Simplify enhancers::Cache

- rust/src/enhancers/grammar.rs
- rust/src/enhancers/matchers.rs
- rust/src/enhancers/rules.rs
This rewrites matchers without use of traits or dynamic dispatch. They are actually very easily expressed as an enum because there are so few different cases.
> Rewrite matchers as ADTs

- rust/src/enhancers/actions.rs
- rust/src/enhancers/grammar.rs
Unfortunately these are not quite as simple as `<var_name> = <ident>`—the type of the right-hand side varies based on the variable. In particular, some of them are numbers that we need to parse.
> Rework var actions

- bindings/src/enhancers.rs
- rust/src/enhancers/mod.rs
This solves the mystery why python returns an intermediate list in `get_matching_frame_actions`.
The algorithm has to run in two passes, because caller/callee matchers could observe modifications.
> Apply rules in a second pass 

- bindings/src/enhancers.rs
- python/sentry_ophio/enhancers.pyi
- tests/test_enhancer.py
With the addition of `from_config_structure`, there's no longer really a canonical constructor. I think `parse` is a clearer name for this function.
> Rename Enhancements.__new__ to parse

- bindings/src/enhancers.rs
- rust/src/enhancers/actions.rs
- rust/src/enhancers/frame.rs
- rust/src/enhancers/matchers.rs
This way the `orig_in_app` flag is not touched by the `apply_modifications_to_frame` method.
> Update `orig_/in_app` handling

- bindings/src/enhancers.rs
- rust/src/enhancers/families.rs
- rust/src/enhancers/frame.rs
- rust/src/enhancers/matchers.rs
- rust/src/enhancers/mod.rs
I believe the `families` check is hot enough to warrant such a micro-optimization.
```
enhancers                          fastest       │ slowest       │ median        │ mean
├─ apply_modifications             416.3 µs      │ 1.21 ms       │ 464.4 µs      │ 489.2 µs
├─ apply_modifications             376.9 µs      │ 1.803 ms      │ 412.3 µs      │ 444.9 µs
```
Looks like a ~10% improvement, so why not :-)
> Use a bitfield for `families` and optimize that a bit more

- rust/src/enhancers/cache.rs
- rust/src/enhancers/matchers.rs
- rust/src/enhancers/mod.rs
The `get_or_try_insert` methods on `Cache` were only ever called with one function argument each (as obviously must be the case for consistency reasons). Therefore we just bake those function arguments in directly.
> Make cache methods non-generic

- rust/src/enhancers/cache.rs
- rust/src/enhancers/matchers.rs
- rust/src/enhancers/mod.rs
Forgot about these when I did the frame matchers.
> Cache regexes in exception matchers

- bindings/src/enhancers.rs
- rust/src/enhancers/actions.rs
- rust/src/enhancers/frame.rs
- rust/src/enhancers/mod.rs
- rust/src/enhancers/rules.rs
This reworks the logic for keeping track of which rule last set a frame's `in_app` flag. Instead of relying on the frankly incomprehensible `in_app_changed` function, we now save the rule in the frame every time the `in_app` flag is modified. Then we can simply iterate over the (frame, component) pairs in `Enhancements::update_frame_components_contributions` and set the hints based on the saved rule.
As a consequence, the `orig_in_app` field on `Frame` becomes unnecessary.
> Fix tracking of which rule last updated in_app

- .github/workflows/ci.yml
- Makefile
- pyproject.toml
- python/sentry_ophio/enhancers.pyi
- requirements.txt
- tests/conftest.py
- tests/test_enhancer.py
I used `isort` to sort all of the imports (not enforced in CI yet), as well as `black` to reformatted the test files. I haven’t enabled that in CI either, as it would currently reformatted all the `pyi` files as well in a way that makes them unreadable :-(
> Add `mypy` to CI, along  with more python tooling

- Cargo.lock
- bindings/Cargo.toml
- bindings/src/lib.rs
- pyproject.toml
- python/sentry_ophio/__init__.py
- python/sentry_ophio/enhancers.py
- python/sentry_ophio/proguard.py
I believe I understand the problem with packages/modules now.
A python *package* is a directory with a `__init__.py`, and a *module* is just a python file.
When writing `import`s in Python, the *parent* of that path *must* be a package.
So `from this_is_a_package.this_is_a_module import *` works. Whereas `from this_is_a_parent_module.this_is_a_child_module import *` does not.
However it would seem that one limitation of python extension modules is that they are in fact *modules*, and not *packages*. So you cannot *directly* import stuff from their sub-modules.
Long story short, the workaround I found online was manipulating the global `sys.modules` directory to make this work, however that messes with tools like `Pylance` in VS Code.
Instead, I now just export a flat list of classes (and …
> Rework python package/module exporting

- rust/src/enhancers/cache.rs
[According to the docs](https://docs.sentry.io/product/data-management-settings/event-grouping/stack-trace-rules/#matchers), `function` and `module are supposed to match case-sensitively, and `path` and `package` are supposed to match case-insensitively. Fortunately, this neatly lines up with whether the match is path-like.
> Fix glob pattern case sensitivity

- README.md
- bindings/Cargo.toml
- pyproject.toml
Turns out we are developing locally and testing with 3.10, but actually target 3.9:
https://github.com/getsentry/pypi/issues/623
So lets downgrade here as well so that we can publish and uplift automatically.
> Downgrade Python requirement

- rust/src/enhancers/grammar.rs
- rust/src/enhancers/matchers.rs
This would in theory fix https://sentry.sentry.io/issues/4934804272/ in the sense that we keep the current behavior.
Although the current behavior is to silently ignore the rule and always assume it does not match, which happens here:
https://github.com/getsentry/relay/blob/e9a7e18983c699fc6bc9024e49190a8e8c678c8c/relay-common/src/glob.rs#L62-L67
I’m not really happy with this solution, as the grammar accepts the matcher, but the matcher itself silently fails all the time :-(
> Ignore Broken Glob matchers

- rust/src/enhancers/frame.rs
- rust/src/enhancers/grammar.rs
- rust/src/enhancers/matchers.rs
Similar to #38, the Python parser accepts more invalid things that just won’t ever match.
This is another one of those cases.
> Silently accept invalid `app` matcher

- Cargo.lock
- rust/Cargo.toml
- rust/src/enhancers/cache.rs
- rust/src/enhancers/config_structure.rs
- rust/src/enhancers/grammar.rs
- rust/src/enhancers/matchers.rs
- rust/src/enhancers/mod.rs
Or at least mostly recursive.
I got very annoyed at the bad error messages in the `nom` parser, so I wrote an RD parser by hand. It uses `anyhow` for errors and as a consequence, they are pretty nice. Performance is, in my tests, pretty much exactly the same as before.
I think it's a matter of taste which version is more readable; this one also isn't documented at all yet.
The first commit is a version that mutates the input instead of returning a new slice every time. I haven't decided yet which I like better.
Additionally, caches have been split up; this is because passing the entire cache to the parser for regex parsing purposes would otherwise lead to ownership problems. Interestingly, at least in the benchmark it doesn't matter if we cache regex creation in the parser—the rule …
> ref(enhancers): Replace nom parser with handwritten recursive descent

- rust/src/enhancers/rules.rs
I got confused because `update_frame_components_contributions` does not currently run any `exception_matchers`, and thus a Rule is being applied that has *only* an exception matcher, but not a frame matcher.
> Document matching behavior without any matcher

- Cargo.lock
- bindings/Cargo.toml
- bindings/src/enhancers.rs
- bindings/src/lib.rs
- bindings/src/proguard.rs
- python/sentry_ophio/enhancers.pyi
- tests/test_enhancer.py
This opts into the new PyO3 0.21 beta, which is scheduled for a release this month.
It also switcher to the new `Bound` API which should be more performant.
Also switches from using an `Iterator` for the `match_frame`s to a `List`, as I hope that will be slightly more performant.
> Switch to new PyO3 `Bound` API

- bindings/src/enhancers.rs
- bindings/src/lib.rs
- python/sentry_ophio/enhancers.py
- python/sentry_ophio/enhancers.pyi
- rust/src/enhancers/actions.rs
- rust/src/enhancers/frame.rs
- rust/src/enhancers/grammar.rs
- rust/src/enhancers/mod.rs
- tests/test_enhancer.py
This ports the handling of `min-frames` to the Rust code, adds `exception_data` matching, and changes some internal types around.
The PR also contains a typo-fix that came from #40. We tested this PR together with https://github.com/getsentry/sentry/pull/66587 which runs the Sentry unit tests without any observable differences.
> Add the complete `assemble_stacktrace_component` logic

- bindings/src/enhancers.rs
- rust/src/enhancers/actions.rs
- rust/src/enhancers/frame.rs
- rust/src/enhancers/matchers.rs
- rust/src/enhancers/mod.rs
- rust/src/enhancers/rules.rs
- tests/test_enhancer.py
Instead of using `in_app_last_changed`, this rather takes the `orig_in_app` value directly from Python, and replicates the `hint` attaching logic exactly as it exists in Python.
> Fully replicate `in_app` hint logic

- Cargo.lock
- bindings/src/ketama.rs
- bindings/src/lib.rs
- python/sentry_ophio/ketama.py
- python/sentry_ophio/ketama.pyi
- rust/Cargo.toml
- rust/src/ketama.rs
- rust/src/lib.rs
- tests/test_ketama.py
This pretty much does https://github.com/getsentry/sentry/issues/68599 by porting the `twemcache` ketama code to Rust, while simplifying it quite a bit.
Our production config does not use different server weights, so all the weight-dependant code was removed.
> Implement a crc32/Ketama-based consistent hashing scheme

- .envrc
- bindings/src/enhancers.rs
- python/sentry_ophio/enhancers.pyi
- rust/src/enhancers/actions.rs
- rust/src/enhancers/config_structure.rs
- rust/src/enhancers/grammar.rs
- rust/src/enhancers/mod.rs
- tests/test_enhancer.py
This was part of hierarchical grouping, which has been deprecated and removed.
It is thus time to also remove these fields and rules from the Rust code.
> Remove `is_sentinel/prefix_frame` from Enhancers

- .github/workflows/build.yml
This will help to determine that the build process has not regressed in pull requests.
Notice that the upload step is skipped:
> Run release builds on PRs

- .github/workflows/build.yml
Uses artifacts/merge to merge together multiple artifacts from different jobs into the single one named github.sha that craft expects.
Summarily, upload-artifact v3 is deprecated but v4 doesn't support mutating an artifact with the name name by uploading different filepaths to the same artifact. Because we need a single artifact "github.sha", we have to use actions/merge to create it. Alternatively craft could be modified but this is the easiest way forward and I like the idea of a unified artifact, it makes craft simpler.
ref: https://github.com/getsentry/craft/issues/552
> ci: update artifact actions to v4

- rust/src/enhancers/mod.rs
This expands the allowed enhancement versions to allow 3, in order to enable the split enhancements experiment in Sentry.
> fix(grouping): Allow enhancements version 3

- .gitignore
OSX creates `.DS_Store` files to save visual info about the folders in which they reside, but they're unique to each machine, so we shouldn't be committing them.
> chore(dev): Add `.DS_Store` files to `.gitignore`

- Makefile
As someone unfamiliar with the rust ecosystem, I kept forgetting and having to look up the build command `maturin develop`. This PR therefore adds a makefile alias for it, `make build`.
> feat(dev): Add `make build` command

- pyproject.toml
Pypi expects us to declare the license file according to [PEP 639](https://peps.python.org/pep-0639/), but maturin [doesn't yet support it](https://github.com/PyO3/maturin/issues/2531#issuecomment-2833172453). Another maturin user posted [a workaround](https://github.com/PyO3/maturin/issues/2531#issuecomment-2832632196), to try to get maturin to include the license file in the tarball, which this PR implements.
(There is a [draft PR](https://github.com/PyO3/maturin/pull/2571) in the maturin repo to add support for PEP 639, but as of now it seems incomplete. If/when that's completed, merged, and released, we can update maturin and then fix the license specification as is done in https://github.com/getsentry/ophio/pull/80.)
> fix(dev): Try workaround to get maturin to include license file
